name: Deploy event processing architecture

on:
  workflow_dispatch: # manuel https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

env:
  # set this to the path to your web app project, defaults to the repository root
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    
  # Function app name
  FUNCTION_APP_NAME: fbu-function-processing
  # resource group name
  RESOURCE_GROUP_NAME: fbu-apps
  # terraform storage name
  TERRAFORM_STORAGE_NAME: terraformstoragefbu
  # terraform container name
  TERRAFORM_CONTAINER_NAME: terraform
  # terraform key
  TERRAFORM_KEY: terraform.tfstate
  # location
  LOCATION: westeurope

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
             
  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create resource group
      run: az group create --location ${{ env.LOCATION }} --name "${{ env.RESOURCE_GROUP_NAME }}"

    - name: Create storage account for terraform backend
      run: az storage account create --name "${{ env.TERRAFORM_STORAGE_NAME }}" --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --location "${{ env.LOCATION }}" --sku "Standard_LRS"

    - name: Create storage container for terraform backend
      run: az storage container create --name "${{ env.TERRAFORM_CONTAINER_NAME }}" --account-name "${{ env.TERRAFORM_STORAGE_NAME }}"
    
    - name: Replace terraform backend configuration
      uses: flcdrg/replace-multiple-action@v1
      with:
        files: './Deploy/*.tf'
        find: '[{ "$RESOURCE_GROUP_NAME": "${{ env.RESOURCE_GROUP_NAME }}", "$TERRAFORM_STORAGE_NAME": "${{ env.TERRAFORM_STORAGE_NAME }}" , "$TERRAFORM_CONTAINER_NAME": "${{ env.TERRAFORM_CONTAINER_NAME }}" , "$TERRAFORM_KEY": "${{ env.TERRAFORM_KEY }}" }]'
    
    # Install the needed version of Terraform cli
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
    
    - name: Terraform Init
      run: terraform init
      working-directory: Deploy
      shell: bash
      
    # https://www.terraform.io/cli/commands/validate
    - name: Terraform Validate
      run: |
        terraform validate
    # Generates an execution plan for Terraform with tfplan file https://www.terraform.io/cli/commands/plan
    - name: Terraform Plan
      run: |
        terraform plan -lock=false -out=monplan.tfplan
              
    # apply a execution plan https://www.terraform.io/cli/commands/apply      
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -lock=false "monplan.tfplan"
